FROM node:24-bookworm-slim AS build

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json* ./
RUN npm install -g npm@11.6.2 && npm ci

COPY frontend/ ./

ARG PLACEHOLDER_MODE=true
ARG SITE_URL=https://example.com
ARG CONTACT_EMAIL=name@example.com
ARG CONTACT_LINKEDIN_URL=https://linkedin.com/
ARG CONTACT_GITHUB_URL=https://github.com/
ARG LEGAL_FULL_NAME="Your Legal Name"
ARG LEGAL_ADDRESS_LINE_1="Street 1"
ARG LEGAL_ADDRESS_LINE_2="12345 City"
ARG LEGAL_ADDRESS_LINE_3=""
ARG LEGAL_COUNTRY="Country"
ARG LEGAL_EMAIL=name@example.com
ARG LEGAL_HOSTING_PROVIDER="Hosting Provider"
ARG LEGAL_PROCESSING_LOCATION="EU/EEA"

ENV PLACEHOLDER_MODE=$PLACEHOLDER_MODE
ENV SITE_URL=$SITE_URL
ENV CONTACT_EMAIL=$CONTACT_EMAIL
ENV CONTACT_LINKEDIN_URL=$CONTACT_LINKEDIN_URL
ENV CONTACT_GITHUB_URL=$CONTACT_GITHUB_URL
ENV LEGAL_FULL_NAME=$LEGAL_FULL_NAME
ENV LEGAL_ADDRESS_LINE_1=$LEGAL_ADDRESS_LINE_1
ENV LEGAL_ADDRESS_LINE_2=$LEGAL_ADDRESS_LINE_2
ENV LEGAL_ADDRESS_LINE_3=$LEGAL_ADDRESS_LINE_3
ENV LEGAL_COUNTRY=$LEGAL_COUNTRY
ENV LEGAL_EMAIL=$LEGAL_EMAIL
ENV LEGAL_HOSTING_PROVIDER=$LEGAL_HOSTING_PROVIDER
ENV LEGAL_PROCESSING_LOCATION=$LEGAL_PROCESSING_LOCATION

RUN npm run build

FROM nginx:1.29-alpine

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/out /usr/share/nginx/html
